<?php
  //Implements hook_form_FORM_ID_alter() to modify the custom generic form

  function custom_form_form_custom_simple_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
        // Add a checkbox to the login form.
        $form['custom_checkbox'] = [
            '#type' => 'checkbox',
            '#title' => t('Remember me'),
            '#default_value' => 0,
        ];
   }
